modLoader="javafml" #mandatory

loaderVersion="[31,)"

issueTrackerURL="https://github.com/clivet268/MachineBuiltWorld/issues"

[[mods]] #mandatory

    modId="machinebuiltworld"
    version="1.15.2-1.0.5"
    displayName="Machine Built World" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/machine-built-world"
    logoFile="logo.png"
    credits="Thanks fur myself"
    authors="Clivet268"
    description='''e'''

[[dependencies.machinebuiltworld]] #optional
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"

[[dependencies.machinebuiltworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.machinebuiltworld]]
    modId="mekanism"
    mandatory=false
    versionRange="[${top_version},)"
    ordering="NONE"
    side="BOTH"